### ISSUE TITLE
Uncaught TypeError: Cannot read property 'didResolveConflict' of undefined

### ISSUE THREAD

**Issue by istinspring** [smashwilson/merge-conflicts#117]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.16.0-29-generic
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.2.9

### Stack Trace

Uncaught TypeError: Cannot read property 'didResolveConflict' of undefined

```
At /home/istinspring/.atom/packages/merge-conflicts/lib/merge-conflicts-view.coffee:118

TypeError: Cannot read property 'didResolveConflict' of undefined
  at /home/istinspring/.atom/packages/merge-conflicts/lib/merge-conflicts-view.coffee:118:13
  at proc.process.exit (/home/istinspring/.atom/packages/merge-conflicts/lib/git-bridge.coffee:145:11)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:469:12)

```

### Commands

```
  4x -2:33.1 core:select-down (atom-text-editor.editor.conflicted.is-focused)
  3x -2:31.0 core:select-up (atom-text-editor.editor.conflicted.is-focused)
  2x -2:29.5 core:select-down (atom-text-editor.editor.conflicted.is-focused)
     -2:27.9 editor:consolidate-selections (atom-text-editor.editor.conflicted.is-focused)
     -2:27.9 core:cancel (atom-text-editor.editor.conflicted.is-focused)
     -1:29.1 core:paste (atom-text-editor.editor)
     -1:05.6 editor:consolidate-selections (atom-text-editor.editor.conflicted.is-focused)
     -1:05.6 core:cancel (atom-text-editor.editor.conflicted.is-focused)
     -1:04.6 editor:consolidate-selections (atom-text-editor.editor.conflicted.is-focused)
     -1:04.6 core:cancel (atom-text-editor.editor.conflicted.is-focused)
     -1:01.8 command-palette:toggle (atom-text-editor.editor.conflicted.is-focused)
 10x -0:57.6 core:backspace (atom-text-editor.editor.mini)
     -0:40.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:40.1 core:cancel (atom-text-editor.editor.mini)
  2x -0:38.3 settings-view:open (atom-text-editor.editor.conflicted.is-focused)
     -0:00.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      "*.sublime-*",
      "__pycache__"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "projectHome": "/home/istinspring/projects"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
editorconfig, v0.3.0
linter, v0.10.1
linter-jshint, v0.1.0
linter-pylint, v0.2.0
merge-conflicts, v1.2.9
monokai, v0.11.0
project-manager, v1.15.0
terminal-status, v1.3.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by clarkritchie** [comment]
I also see this error.

**Comment by rgcalsaverini** [comment]
I experience this aswell.

**Comment by cloudbring** [comment]
I have seen this error as well.

**Comment by smashwilson** [comment]
Replicated and corrected. :dart: Silly mistake, this one will be fixed in the next release.

Thanks for the reports! :bow:
