### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by wjn** [smashwilson/merge-conflicts#128]
Merge-conflicts works for all other atom users on my team except me. I've never been able to get it working.

[Enter steps to reproduce below:]

1. Packages > Merge Conflicts > Detect

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.2.10

### Stack Trace

Uncaught Error: spawn EACCES

```
At child_process.js:1160

Error: spawn EACCES
  at exports._errnoException (util.js:753:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
  at Function.GitBridge.process (/Users/winielsen/.atom/packages/merge-conflicts/lib/git-bridge.coffee:18:27)
  at Function.GitBridge.withConflicts (/Users/winielsen/.atom/packages/merge-conflicts/lib/git-bridge.coffee:96:13)
  at Function.module.exports.MergeState.read (/Users/winielsen/.atom/packages/merge-conflicts/lib/merge-state.coffee:21:15)
  at Function.MergeConflictsView.detect (/Users/winielsen/.atom/packages/merge-conflicts/lib/merge-conflicts-view.coffee:137:16)
  at /Users/winielsen/.atom/packages/merge-conflicts/lib/merge-conflicts.coffee:25:28
  at Function.GitBridge.locateGitAnd (/Users/winielsen/.atom/packages/merge-conflicts/lib/git-bridge.coffee:27:7)
  at atom-workspace.<anonymous> (/Users/winielsen/.atom/packages/merge-conflicts/lib/merge-conflicts.coffee:23:17)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -3:51.1 find-and-replace:show (input.hidden-input)
  3x -3:45.2 core:delete (input.hidden-input)
     -3:38.3 core:save (input.hidden-input)
     -2:17.1 core:delete (input.hidden-input)
     -2:15.3 core:undo (input.hidden-input)
     -1:33.9 core:backspace (input.hidden-input)
     -1:28.6 core:undo (input.hidden-input)
     -1:25.5 find-and-replace:show (input.hidden-input)
     -1:22.4 core:confirm (input.hidden-input)
     -0:58.0 settings-view:open (input.hidden-input)
     -0:35.1 editor:move-to-first-character-of-line (input.hidden-input)
     -0:34.0 core:confirm (input.hidden-input)
     -0:01.6 merge-conflicts:detect (input.hidden-input)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "jslint",
      "jshint",
      "timecop",
      "Zen",
      "atom-lint",
      "atom-jshint",
      "dash",
      "ember-cli-helper",
      "git-blame",
      "git-log",
      "angularjs",
      "lorem-ipsum",
      "indent-guide-improved"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "merge-conflicts": {
    "gitPath": "/usr/local/git/"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
autoclose-html, v0.15.0
file-icons, v1.4.10
git-tab-status, v1.5.3
jsonlint, v1.0.1
language-coffee-script-angular, v2.2.0
linter-coffeelint, v0.1.7
linter-scss-lint, v0.0.11
merge-conflicts, v1.2.10
minifier, v0.2.0
pain-split, v1.3.1
pretty-json, v0.3.2
sassbeautify, v0.2.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by smashwilson** [comment]
It looks like your `gitPath` is set to a directory, not the `git` binary itself:

```
{
  "merge-conflicts": {
    "gitPath": "/usr/local/git/"
  }
}
```

Try setting it to `/usr/local/git/bin/git` (on the merge-conflicts settings page) and give it another shot.

**Comment by shreeshkatyayan** [comment]
@smashwilson thanks for bringing that to notice. Also, the default is set to `/usr/local/git/bin`. Why not set it to the binary itself?

**Comment by smashwilson** [comment]
@shreeshkatyayan Hmm, looking [at the source](https://github.com/smashwilson/merge-conflicts/blob/master/lib/main.coffee#L35-L38) it shouldn't have a default at all:

```coffeescript
    gitPath:
      type: 'string'
      default: ''
      description: 'Absolute path to your git executable.'
```

And the [default search paths](https://github.com/smashwilson/merge-conflicts/blob/master/lib/git/shellout.js#L175-L178) all look like they point the binary too:

```javascript
  let search = [
    'git', // Search the inherited execution PATH. Unreliable on Macs.
    '/usr/local/bin/git', // Homebrew
    '"%PROGRAMFILES%\\Git\\bin\\git"', // Reasonable Windows default
    '"%LOCALAPPDATA%\\Programs\\Git\\bin\\git"' // Contributed Windows path
  ];
```

Where are you seeing `/usr/local/git/bin`? Does the Settings view specify that as the default... ? I'm not sure where that could be coming from 🤔
