### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of null

### ISSUE THREAD

**Issue by nallie** [smashwilson/merge-conflicts#129]

**Comment by bprosnitz** [comment]
I hit this as well at .atom/packages/merge-conflicts/lib/git-bridge.coffee:66

**Comment by bprosnitz** [comment]
This seems to occur when the atom project isn't rooted at a git repo (e.g. has git repos inside). This is user error, but it would be useful to have an error message explaning.

**Comment by smashwilson** [comment]
@bprosnitz Hmm, thanks for the extra info.

**Comment by Xean** [comment]
Same for me. I tried to edit a remote file (using [remote-edit](https://atom.io/packages/remote-edit)).

**Comment by sdornan** [comment]
Also happened to me when hitting Detect on a file with merge conflicts.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of null

```
At /Users/sam/.atom/packages/merge-conflicts/lib/git-bridge.coffee:66

TypeError: Cannot read property 'getPath' of null
  at Function.GitBridge._repoGitDir (/Users/sam/.atom/packages/merge-conflicts/lib/git-bridge.coffee:66:53)
  at Function.GitBridge.isRebasing (/Users/sam/.atom/packages/merge-conflicts/lib/git-bridge.coffee:168:13)
  at Function.module.exports.MergeState.read (/Users/sam/.atom/packages/merge-conflicts/lib/merge-state.coffee:20:21)
  at Function.MergeConflictsView.detect (/Users/sam/.atom/packages/merge-conflicts/lib/merge-conflicts-view.coffee:137:16)
  at /Users/sam/.atom/packages/merge-conflicts/lib/merge-conflicts.coffee:25:28
  at /Users/sam/.atom/packages/merge-conflicts/lib/git-bridge.coffee:42:9
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -0:27.3 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:25.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:25.1 core:cancel (atom-text-editor.editor.mini)
     -0:19.6 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:16.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:16.9 core:cancel (atom-text-editor.editor.mini)
     -0:02.3 merge-conflicts:detect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.9.0
color-picker, v1.6.0
editorconfig, v0.3.3
language-jade, v0.3.0
linter, v0.12.0
linter-jshint, v0.1.1
linter-less, v0.3.1
linter-pep8, v0.1.0
merge-conflicts, v1.3.0
minimap, v4.7.6
monokai, v0.13.0
tabs-to-spaces, v0.9.2
travis-ci-status, v0.13.0

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
Alright, the next release includes a fix for the general case where you attempt to detect conflicts in a project that doesn't have a git repository at all. The underlying issue is atom/atom#2203; once that's fixed merge-conflicts should handle non-project-root git repositories as it is. Thanks for the reports, and especially the diagnosis and the stack trace! :sparkles:
