### ISSUE TITLE
Failed to activate the merge-conflicts package

### ISSUE THREAD

**Issue by Huaraz2** [smashwilson/merge-conflicts#130]
[Enter steps to reproduce below:]

This error pops up when I open atom, be it in normal or dev mode

**Atom Version**: 0.187.0-abf368e
**System**: linux 3.16.0-31-generic
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.2.10

### Stack Trace

Failed to activate the merge-conflicts package

```
At '0' is not a valid selector in /home/huaraz2/.atom/packages/merge-conflicts/package.json

Error: '0' is not a valid selector in /home/huaraz2/.atom/packages/merge-conflicts/package.json
    at exports.validateSelector (/usr/share/atom/resources/app/src/selector-validator.js:36:13)
    at CommandRegistry.module.exports.CommandRegistry.add (/usr/share/atom/resources/app/src/command-registry.js:50:9)
    at /usr/share/atom/resources/app/src/package.js:722:74
    at Package.<anonymous> (/usr/share/atom/resources/app/src/package.js:750:21)
    at Package.module.exports.Package.subscribeToActivationCommands (/usr/share/atom/resources/app/src/package.js:753:12)
    at /usr/share/atom/resources/app/src/package.js:219:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:465:21)
    at /usr/share/atom/resources/app/src/package-manager.js:446:29
  at /home/huaraz2/.atom/packages/merge-conflicts/package.json:1:1
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "highlight-line"
    ],
    "themes": [
      "atom-dark-ui",
      "the--matrix-syntax"
    ],
    "audioBeep": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.6.0
background-matrix, v0.0.3
color-picker, v1.5.0
language-r, v0.1.1
linter, v0.12.0
minimap, v4.6.0
script, v2.18.0
the--matrix-syntax, v1.0.0

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
I bet that #132 took care of this one for you. Can you retry with merge-conflicts 1.3.0?

**Comment by smashwilson** [comment]
As far as I know, merge-conflicts should be ready for Atom 1.0. Open me a new issue if you see this again with 1.3.2 or greater!
