### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ours' of null

### ISSUE THREAD

**Issue by mrkwse** [smashwilson/merge-conflicts#133]
[Enter steps to reproduce below:]

1. Use ctrl-m and arrow beyond first/last conflict.
2. Tries to read theirs and ours from a null conflict. 

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.2.10

### Stack Trace

Uncaught TypeError: Cannot read property 'ours' of null

```
At /Users/mwuk/.atom/packages/merge-conflicts/lib/conflict-marker.coffee:194

TypeError: Cannot read property 'ours' of null
  at ConflictMarker.module.exports.ConflictMarker.focusConflict (/Users/mwuk/.atom/packages/merge-conflicts/lib/conflict-marker.coffee:194:18)
  at ConflictMarker.module.exports.ConflictMarker.previousUnresolved (/Users/mwuk/.atom/packages/merge-conflicts/lib/conflict-marker.coffee:166:8)
  at atom-text-editor.subs.add.atom.commands.add.merge-conflicts:previous-unresolved (/Users/mwuk/.atom/packages/merge-conflicts/lib/conflict-marker.coffee:56:50)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:32.4 merge-conflicts:accept-theirs (atom-text-editor.editor)
     -0:26.5 core:move-down (atom-text-editor.editor)
     -0:26.2 core:move-up (atom-text-editor.editor)
     -0:24.5 merge-conflicts:previous-unresolved (atom-text-editor.editor)
     -0:22.5 merge-conflicts:accept-theirs (atom-text-editor.editor)
     -0:17.2 merge-conflicts:previous-unresolved (atom-text-editor.editor)
     -0:15.8 merge-conflicts:accept-theirs (atom-text-editor.editor)
     -0:11.8 merge-conflicts:next-unresolved (atom-text-editor.editor)
     -0:10.9 merge-conflicts:accept-theirs (atom-text-editor.editor)
     -0:07.2 merge-conflicts:previous-unresolved (atom-text-editor.editor.conflicted.is-focused)
     -0:06.3 merge-conflicts:accept-theirs (atom-text-editor.editor.conflicted.is-focused)
     -0:05.4 merge-conflicts:next-unresolved (atom-text-editor.editor.conflicted.is-focused)
     -0:04.4 core:backspace (atom-text-editor.editor.conflicted.is-focused)
     -0:03.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.conflicted.is-focused)
     -0:02.3 merge-conflicts:previous-unresolved (atom-text-editor.editor.conflicted.is-focused)
     -0:00.8 merge-conflicts:accept-theirs (atom-text-editor.editor.conflicted.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-2048",
      "vim-mode"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atom-handlebars, v0.4.0
autocomplete-plus, v2.4.2
color-picker, v1.4.4
compare-files, v0.4.1
language-erlang, v2.0.0
merge-conflicts, v1.2.10
minimap, v4.6.0
minimap-color-highlight, v4.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
minimap-selection, v4.2.0
project-palette-finder, v2.4.16

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
This should be fixed in the next release. Let me know if it still pops up for you after 1.3.1 ships :smile:
