### ISSUE TITLE
Uncaught TypeError: Cannot read property 'findKeyBindings' of undefined

### ISSUE THREAD

**Issue by westmark** [smashwilson/merge-conflicts#142]
[Enter steps to reproduce below:]

1. Open a file with git conflicts
2. Run the "Merge Conflicts: Detect" command

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'findKeyBindings' of undefined

```
At /Users/westmark/.atom/packages/merge-conflicts/lib/covering-view.coffee:62

TypeError: Cannot read property 'findKeyBindings' of undefined
  at SideView.CoveringView.prependKeystroke (/Users/westmark/.atom/packages/merge-conflicts/lib/covering-view.coffee:62:27)
  at SideView.module.exports.SideView.initialize (/Users/westmark/.atom/packages/merge-conflicts/lib/side-view.coffee:23:6)
  at SideView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at SideView.CoveringView (/Users/westmark/.atom/packages/merge-conflicts/lib/covering-view.coffee:8:3)
  at new SideView (/Users/westmark/.atom/packages/merge-conflicts/lib/side-view.coffee:7:3)
  at new ConflictMarker (/Users/westmark/.atom/packages/merge-conflicts/lib/conflict-marker.coffee:20:31)
  at Function.MergeConflictsView.markConflictsIn (/Users/westmark/.atom/packages/merge-conflicts/lib/merge-conflicts-view.coffee:158:9)
  at /Users/westmark/.atom/packages/merge-conflicts/lib/merge-conflicts-view.coffee:146:21
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
  at /Users/westmark/.atom/packages/merge-conflicts/lib/merge-conflicts-view.coffee:145:43
  at /Users/westmark/.atom/packages/merge-conflicts/lib/merge-state.coffee:25:9
  at exitHandler (/Users/westmark/.atom/packages/merge-conflicts/lib/git-bridge.coffee:92:9)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:12.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
  2x -0:10.8.0 core:move-down (atom-text-editor.editor.mini)
     -0:10.5.0 core:confirm (atom-text-editor.editor.mini)
     -0:06.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:05.9.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:05.9.0 core:cancel (atom-text-editor.editor.mini)
     -0:05.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.1.0 core:move-down (atom-text-editor.editor.mini)
     -0:01.6.0 core:confirm (atom-text-editor.editor.mini)
     -0:01.5.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshint",
      "autocomplete"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/westmark/Documents/projects"
  },
  "merge-conflicts": {
    "gitPath": "/usr/local/bin/git"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-handlebars, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
color-picker, v1.7.0
docs-snippets, v0.8.0
file-types, v0.3.0
gulp-snippets, v0.6.1
highlight-selected, v0.9.2
language-glsl, v2.0.0
language-jade, v0.4.0
linter, v0.12.1
linter-eslint, v0.5.3
merge-conflicts, v1.3.1
minimap, v4.8.0
monokai, v0.14.0
pretty-json, v0.3.3
project-manager, v1.15.5
react, v0.11.8
sync-settings, v0.2.2

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
Thanks! This should be fixed in #144, which was just released in 1.3.2.
