### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendToTop' of undefined

### ISSUE THREAD

**Issue by wchill** [smashwilson/merge-conflicts#148]
1. Open javascript source file
2. Attempt to detect conflicts

**Atom Version**: 0.209.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'appendToTop' of undefined

```
At C:\Users\Eric Ahn\.atom\packages\merge-conflicts\lib\error-view.coffee:32

TypeError: Cannot read property 'appendToTop' of undefined
  at module.exports (C:\Users\Eric Ahn\.atom\packages\merge-conflicts\lib\error-view.coffee:32:23)
  at C:\Users\Eric Ahn\.atom\packages\merge-conflicts\lib\merge-conflicts.coffee:24:16
  at C:\Users\Eric Ahn\.atom\packages\merge-conflicts\lib\git-bridge.coffee:48:9
  at triggerExitCallback (C:\Users\Eric Ahn\AppData\Local\atom\app-0.209.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\Eric Ahn\AppData\Local\atom\app-0.209.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -6:41.9.0 core:paste (atom-text-editor.editor.is-focused)
     -6:40.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:36.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:25.8.0 find-and-replace:show (ul.list-inline.tab-bar.inset-panel)
  4x -1:24.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.4.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.4
merge-conflicts, v1.3.2

# Dev
No dev packages
```

**Comment by jamiecollinson** [comment]
+1

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.2


### Stack Trace

Uncaught TypeError: Cannot read property 'appendToTop' of undefined

```
At C:\Users\jamie.collinson\.atom\packages\merge-conflicts\lib\error-view.coffee:32

TypeError: Cannot read property 'appendToTop' of undefined
  at module.exports (C:\Users\jamie.collinson\.atom\packages\merge-conflicts\lib\error-view.coffee:32:23)
  at C:\Users\jamie.collinson\.atom\packages\merge-conflicts\lib\merge-conflicts.coffee:24:16
  at C:\Users\jamie.collinson\.atom\packages\merge-conflicts\lib\git-bridge.coffee:48:9
  at triggerExitCallback (C:\Users\jamie.collinson\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\jamie.collinson\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
  6x -2:35.3.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 42x -2:33.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -2:30.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -2:30.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  3x -2:29.6.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -2:29.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.operator-pending-mode)
     -2:27.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -2:27.8.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 25x -2:27.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  4x -2:25.7.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  5x -2:24.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 25x -2:23.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -2:21.6.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
 19x -2:20.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -0:55.4.0 window:toggle-dev-tools (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:03.9.0 merge-conflicts:detect (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "audioBeep": false,
    "disabledPackages": [
      "autocomplete-python",
      "autocomplete-plus-python-jedi"
    ]
  },
  "merge-conflicts": {}
}
```

### Installed Packages

```coffee
# User
merge-conflicts, v1.3.2
seti-syntax, v0.4.0
seti-ui, v0.7.1
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by Braunson** [comment]
**Error**
```
Uncaught TypeError: Cannot read property 'appendToTop' of undefined

C:\Users\braunson\.atom\packages\merge-conflicts\lib\error-view.coffee:32
```

**Stack Trace**
```
TypeError: Cannot read property 'appendToTop' of undefined
  at module.exports (C:\Users\braunson\.atom\packages\merge-conflicts\lib\error-view.coffee:32:23)
  at C:\Users\braunson\.atom\packages\merge-conflicts\lib\merge-conflicts.coffee:24:16
  at C:\Users\braunson\.atom\packages\merge-conflicts\lib\git-bridge.coffee:48:9
  at triggerExitCallback (C:\Users\braunson\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\braunson\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

**Comment by rudygunawan** [comment]
+1 same here.
