### ISSUE TITLE
Uncaught TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by walandemar** [smashwilson/merge-conflicts#161]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'on' of undefined

```
At /Users/waladimir/.atom/packages/merge-conflicts/lib/git-bridge.coffee:105

TypeError: Cannot read property 'on' of undefined
  at Function.GitBridge.withConflicts (/Users/waladimir/.atom/packages/merge-conflicts/lib/git-bridge.coffee:105:17)
  at Function.module.exports.MergeState.read (/Users/waladimir/.atom/packages/merge-conflicts/lib/merge-state.coffee:21:15)
  at Function.MergeConflictsView.detect (/Users/waladimir/.atom/packages/merge-conflicts/lib/merge-conflicts-view.coffee:137:16)
  at /Users/waladimir/.atom/packages/merge-conflicts/lib/merge-conflicts.coffee:25:28
  at Function.GitBridge.locateGitAnd (/Users/waladimir/.atom/packages/merge-conflicts/lib/git-bridge.coffee:27:7)
  at atom-workspace.<anonymous> (/Users/waladimir/.atom/packages/merge-conflicts/lib/merge-conflicts.coffee:23:17)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -1:51.8.0 core:close (atom-text-editor.editor.is-focused)
     -1:49.6.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-atom-dark-ui)
     -1:22.4.0 merge-conflicts:detect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:43.2.0 settings-view:open (atom-text-editor.editor.is-focused)
  4x -0:33.1.0 core:backspace (atom-text-editor#merge-conflicts.gitPath.editor.mini.is-focused)
  2x -0:25.7.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "autocomplete-plus",
      "jslint",
      "jsonlint",
      "jshint"
    ]
  },
  "merge-conflicts": {
    "gitPath": "/usr/local/git"
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
atom-handlebars, v1.0.0
autoclose-html, v0.18.0
emmet, v2.3.12
highlight-selected, v0.10.1
language-javascript-jsx, v0.3.6
linter, v1.1.0
linter-stylint, v2.0.0
merge-conflicts, v1.3.2
monokai, v0.14.0
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
Ah - the `BufferedProcess` API had changed and I hadn't noticed it. This was fixed in #163 and shipped in 1.3.3. An upgrade should deal with this for you :sparkles: 

_Sidenote: the keymaps have been changed to use **alt-m** chords instead of ctrl-m ones, and some are reporting errors using the old keybindings after upgrading and before restarting Atom._
