### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Eschon** [smashwilson/merge-conflicts#168]
I've posted this in #119 before but it appears to be a different problem so I opened a separate issue.

I resolved my merge-conflicts and then staged and committed my changes using a GIT-GUI when I tried to quit merge-conflicts using the quit button on the bottom panel this error occurred and the bottom panel won't disappear.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.3

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/egon/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:122

TypeError: undefined is not a function
  at MergeConflictsView.finish (/Users/egon/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:122:7)
  at MergeConflictsView.quit (/Users/egon/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:86:6)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -9:37.9.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -9:36.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:36.1.0 merge-conflicts:detect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -9:13.7.0 core:save (atom-text-editor.editor.conflicted.is-focused)
 12x -8:59.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:44.8.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -8:44.8.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -8:43 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -8:43 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -8:41.7.0 core:save (atom-text-editor.editor.is-focused)
     -4:15.8.0 settings-view:open (a.btn-issue.btn.btn-error)
     -0:04.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:03.5.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.0.0
atom-ternjs, v0.6.8
linter, v1.2.4
linter-clojure, v0.0.5
linter-csslint, v0.0.14
linter-jscs, v1.12.0
linter-jshint, v1.0.5
linter-rubocop, v0.2.7
linter-xmllint, v0.0.7
merge-conflicts, v1.3.3
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by maaarghk** [comment]
I'm getting the same error when using the Detect function. Seems to continue without issue though.

**Comment by Eschon** [comment]
@maaarghk have you compared the stack traces? Undefined is not a function is somewhat generic so it could happen for a completely different reason.

**Comment by maaarghk** [comment]
Yeah, sorry - good point, it does look completely different. I'll open another issue / do a search.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.3


### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/mark/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:158

TypeError: undefined is not a function
  at Function.MergeConflictsView.detect (/Users/mark/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:158:22)
  at /Users/mark/.atom/packages/merge-conflicts/lib/main.coffee:27:28
  at /Users/mark/.atom/packages/merge-conflicts/lib/git-bridge.coffee:42:9
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -4:13.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:59.2.0 editor:newline (atom-text-editor.editor.is-focused)
 47x -3:55.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:54 core:move-right (atom-text-editor.editor.is-focused)
     -2:53.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:51.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:49.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:44.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:39.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -2:39.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:39.9.0 editor:indent (atom-text-editor.editor.is-focused)
     -2:38.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:22.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:21.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.7.0 application:minimize (atom-text-editor.editor.is-focused)
     -0:00.9.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "monokai"
    ]
  },
  "merge-conflicts": {}
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.0
atomatigit, v1.5.3
auto-indent, v0.5.0
language-apache, v1.3.0
language-ini, v1.11.0
merge-conflicts, v1.3.3
monokai, v0.15.0
project-manager, v1.15.11
unity-ui, v2.0.11

# Dev
No dev packages
```

**Comment by Knetic** [comment]
+1 I'm getting this too. I had conflicts, rolled back changes in a shell, now can't get rid of the merge conflict pane in atom because of this.

**Comment by smashwilson** [comment]
#167 should deal with @Eschon's original problem; there was a bit of dead code that was triggering that stacktrace. I'm not entirely certain how a bad marker slipped into the `@markers` collection but looking at the source we shouldn't need to track them there anyway.

This should be fixed in the next release :sparkles:

**Comment by Knetic** [comment]
Can confirm, my case (same as Eschons, given the line numbers) doesn't repro anymore. :+1:
