### ISSUE TITLE
Git add failed: exit code 128 (solved by itself)

### ISSUE THREAD

**Issue by JacopoGobbi** [smashwilson/merge-conflicts#171]
![screen shot 2015-07-22 at 09 35 53 2](https://cloud.githubusercontent.com/assets/11658632/8821417/621b29ba-3055-11e5-9a01-7cf159f46770.png)
After selecting 1 of the two version available for a conflict, I pressed the stage button for the current file. I received the error code, so I started clicking continuosly (like every user would do u.u) until it solved by itself after 20 error messages (who needs bug fixing when you just click 20 times to solve the error?).
Let me know what you think!

**Comment by smashwilson** [comment]
Nuts. I hadn't seen this one for a long time, so I was speculating that it had been fixed upstream, but I suppose not! The original issue was #96, but I'll keep this one open.

**Comment by JacopoGobbi** [comment]
Ok! Thank you @smashwilson. I'm using Atom 1.0.2 on OS X Yosemite 10.10.4 (14E46) if that can help

**Comment by danqing** [comment]
Just saw this and unfortunately it didn't solve itself for me... O.O

**Comment by JacopoGobbi** [comment]
Just happened again. I confirm that If you press stage button more times with a delay of 1-2 seconds it's working after a while... D:
![screen shot 2015-07-24 at 14 40 31 2](https://cloud.githubusercontent.com/assets/11658632/8875586/3758cf7a-3212-11e5-8f83-3b06b1b14281.png)

**Comment by wolfgang42** [comment]
I'm also seeing this occasionally. Once I'm done merging a file it offers to stage; when I click the stage button I get this message. The dialog stays up and if I click stage again it works fine.

**Comment by zwacky** [comment]
also happens every time for me.

**Comment by art-divin** [comment]
This has been happening for me as well, but once I started to save file _before_ trying to stage it from merge-conflicts popup, I was able to workaround this issue.

Probably the problem is that I have code formatter attached to "save" event. When pressing "stage" button from the aforementioned popup, it always shows "128" error code.
But if to separate formatting of the code (pressing CMD+S) from "Stage" event - then everything works OK.

**Comment by martimatix** [comment]
+1

**Comment by pietrovismara** [comment]
+1

**Comment by numaanashraf** [comment]
+1

**Comment by hamishtaplin** [comment]
+1

**Comment by exwar** [comment]
+1 Happens every time for me

**Comment by p-j** [comment]
+1 first time using the merge conflicts plugin, first file processed entirely, impossible to stage.

**Comment by simonlayfield** [comment]
+1

**Comment by wundo** [comment]
+1

**Comment by smashwilson** [comment]
I have a _potential_ fix that'll be included in the next release (1.3.7). Once that's out, I'd appreciate it if those of you who can reproduce reliably can let me know if you still see this! (I'm planning to push it in the next hour or so.)

**Comment by martimatix** [comment]
@smashwilson It's working for me now. Thanks for the fix! :+1:

**Comment by smashwilson** [comment]
Nice! This one's been bugging me for forever, and it only repros for me very, very occasionally.

@exwar You mentioned that it happened every single time for you - if you get a chance, would you mind trying 1.3.7 and seeing if it's still cropping up?

**Comment by smashwilson** [comment]
Nuts - if #193 is any indication, there's still a way this one can happen. :rage:

At least I've fixed it for some of you!

**Comment by JacopoGobbi** [comment]
Anyway, it worked immediately this time for me! I hope you will be able to fix the other issue...

**Comment by sriharshakappala** [comment]
Happening on clicking Stage button after resolving a conflict!

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7


### Stack Trace

Uncaught Error: The index is locked. This might be due to a concurrent or crashed process

```
At /home/harsha/.atom/packages/merge-conflicts/lib/git-bridge.coffee:250

Error: The index is locked. This might be due to a concurrent or crashed process
  at Error (native)
  at Function.GitBridge.add (/home/harsha/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189:15)
  at ResolverView.resolve (/home/harsha/.atom/packages/merge-conflicts/lib/view/resolver-view.coffee:61:15)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -0:38.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:37.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:37.6.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:37.2.0 core:delete (atom-text-editor.editor.is-focused)
  2x -0:36.8.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:36.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:35.7.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -0:35.4.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:34.7.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:34.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:34.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:34.3.0 editor:indent (atom-text-editor.editor.is-focused)
  5x -0:33.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.2.0 merge-conflicts:detect (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-beautify",
      "linter"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-pair, v2.0.10
file-icons, v1.6.11
language-haml, v0.23.6
language-rust, v0.4.5
merge-conflicts, v1.3.7
minimap, v4.16.0

# Dev
No dev packages
```

**Comment by thomasfedb** [comment]
I'm experiencing this issue.

**Comment by AlbertFM** [comment]
+1

**Comment by IanVS** [comment]
This is happening for me on Atom 1.3.0-beta5.

**Comment by keithgordon** [comment]
+1

**Comment by jackbrown** [comment]
Getting the same error clicking 'stage' after resolving conflicts

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7


### Stack Trace

Uncaught Error: The index is locked. This might be due to a concurrent or crashed process

```
At /Users/jackbrown/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189

Error: The index is locked. This might be due to a concurrent or crashed process
    at Error (native)
    at Function.GitBridge.add (/Users/jackbrown/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189:15)
    at ResolverView.resolve (/Users/jackbrown/.atom/packages/merge-conflicts/lib/view/resolver-view.coffee:61:15)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:22.8.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/jackbrown/git",
    "themes": [
      "one-dark-ui",
      "slime"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
color-picker, v2.0.14
emmet, v2.3.17
file-icons, v1.6.13
fold-lines, v0.1.0
foldername-tabs, v0.1.6
js-refactor, v0.6.0
language-babel, v2.6.0
linter, v1.11.3
linter-eslint, v5.2.6
local-history, v3.2.3
merge-conflicts, v1.3.7
overscroll, v0.1.0
pigments, v0.19.3
refactor, v0.6.0
slime, v1.4.0

# Dev
No dev packages
```

**Comment by jacobmischka** [comment]
Still happening for me as well

**Comment by andreas-venturini** [comment]
Workaround for me is to click on "Maybe later" and then on the "Stage" button in the progress overview.

**Comment by tvandervorm** [comment]
Still happens for me too, also happens when I click "stage" in the progress overview. After clicking 3 or 4 times it usually works.

**Comment by esetnik** [comment]
I have the same issue. Out of curiosity are any of you encountering this when Github Desktop is also open on the repo?

**Comment by smashwilson** [comment]
I think my next stab at trying to address this will be using atom/atom#9213 once it's merged, by the way. My best guess is that the git operations we're using are colliding with something that Atom itself is doing with the repository. If I can get rid of GitBridge entirely and use a libgit2-backed object from the official Atom API, maybe it'll resolve this?

**Comment by rm-code** [comment]
Just happened to me too (Atom-Beta 1.5.0 beta1). Fixed itself after I clicked the button again.

**Comment by chibicode** [comment]
Happened to be on 1.4.1 (GitHub Desktop is open @esetnik, didn't try it when I don't use it). @smashwilson https://github.com/atom/atom/pull/9213 seems to have been merged.

**Comment by smashwilson** [comment]
> atom/atom#9213 seems to have been merged.

Excellent. Reworking `GitBridge` to use that *might* make a difference. This is top of my queue the next time I get a chance to do a merge-conflicts hacking day.

> Out of curiosity are any of you encountering this when Github Desktop is also open on the repo?

That's an interesting question. Having another git client open on the same repo polling for status or whatnot could be causing problems.

**Comment by jacobmischka** [comment]
>Out of curiosity are any of you encountering this when Github Desktop is also open on the repo?

I don't have any git client installed besides this atom package and the command line utility.

**Comment by IanVS** [comment]
I am using GitX.

**Comment by chrisbelyea** [comment]
I ran into this issue when I had the repository open in SourceTree on OS X 10.11.3. After closing SourceTree, the merge could complete.

**Comment by rm-code** [comment]
Just like @chrisbelyea I use SourceTree with Atom all the time on OSX 10.11.3 and it seems like the conflict resolves itself when I close SourceTree.

**Comment by bronson** [comment]
I'm getting this too.  Not using any apps.  Manually checking the repo for lockfiles doesn't turn up any.

When I dismiss the error dialog and click "Stage" again, it works.

Any chance there's a code path that fires up two operations async?  That might explain the intermittent nature.

**Comment by bronson** [comment]
Just noticed something...  Sometimes this package opens multiple dialogs saying "Merge Complete!  Press Stage to stage file", both on the same file...

Is there a chance that a previous, hidden dialog has locked git, so the visible one can't actually stage anything?

That would explain what I'm seeing anyway.

**Comment by markogresak** [comment]
> Sometimes this package opens multiple dialogs saying "Merge Complete! Press Stage to stage file", both on the same file...

I believe that's due to multiple conflicts in the same file and the plugin wants to stage each of the conflicts separately. I'm not 100% sure about this, but it's the pattern I noticed.

**Comment by smashwilson** [comment]
The last time I had a chance to work on this package, I did get the native bindings from nodegit working, but they've only shipped in Atom's Beta channel for now.

With that being said, that won't help the case where another git client is open on the same repository and, presumably, polling status or doing some other operation that locks the index.

One thought I've had is to catch the error and retry (with a spinner?) until the index addition goes through. Hacky, but it might do the trick.

**Comment by jacobmischka** [comment]
Unless atom-diff or one of the other builtin git packages would cause it I really don't think that's the problem. I've never had another git cilent open and this happens to me over 50% of the time I try staging using this package.

**Comment by codeVerine** [comment]
+1
