### ISSUE TITLE
Uncaught TypeError: repo.getWorkingDirectory is not a function

### ISSUE THREAD

**Issue by esetnik** [smashwilson/merge-conflicts#182]
[Enter steps to reproduce below:]

1. resolve a file choosing ours

**Atom Version**: 1.0.15
**System**: Mac OS X 10.10.5
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.6

### Stack Trace

Uncaught TypeError: repo.getWorkingDirectory is not a function

```
At /Users/xxx/.atom/packages/merge-conflicts/lib/git-bridge.coffee:228

TypeError: repo.getWorkingDirectory is not a function
    at Function.GitBridge.checkoutSide (/Users/xxx/.atom/packages/merge-conflicts/lib/git-bridge.coffee:228:21)
    at space-pen-div.<anonymous> (/Users/xxx/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:241:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:145:19)
    at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:140:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
    at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
```

### Commands

```
     -3:28.6.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -3:28.3.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -3:27.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:27.1.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -3:26.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -3:26.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:24.8.0 core:move-up (atom-text-editor.editor.is-focused)
 12x -3:24.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:23.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:20.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:57.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:56.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:56.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:36.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:32.9.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
  2x -0:16.6.0 core:copy (atom-text-editor.editor.conflicted.is-focused)
```

### Config

```json
{
  "core": {},
  "merge-conflicts": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.12
editorconfig, v1.2.0
merge-conflicts, v1.3.6
tabs-to-spaces, v0.11.1

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
Thanks :100: for the report and the patience :bow: This fix will ship as part of 1.3.7.
