### ISSUE TITLE
Uncaught Error: The index is locked. This might be due to a concurrent or crashed process

### ISSUE THREAD

**Issue by toxickg** [smashwilson/merge-conflicts#193]
1. Merge any change.
2. Press "Stage" button in the appearing dialog.

**Atom Version**: 1.1.0
**System**: linux 4.2.5-1-ARCH
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7

### Stack Trace

Uncaught Error: The index is locked. This might be due to a concurrent or crashed process

```
At /home/user/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189

Error: The index is locked. This might be due to a concurrent or crashed process
  at Error (native)
  at Function.GitBridge.add (/home/user/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189:15)
  at ResolverView.resolve (/home/user/.atom/packages/merge-conflicts/lib/view/resolver-view.coffee:61:15)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -2:09.8.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
     -0:41.7.0 emmet:increment-number-by-01 (atom-text-editor.editor.conflicted.is-focused)
     -0:41.3.0 emmet:decrement-number-by-01 (atom-text-editor.editor.conflicted.is-focused)
     -0:40.4.0 core:page-up (atom-text-editor.editor.conflicted.is-focused)
     -0:38.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.conflicted.is-focused)
     -0:38 core:move-to-top (atom-text-editor.editor.conflicted.is-focused)
  2x -0:35.9.0 emmet:decrement-number-by-01 (atom-text-editor.editor.conflicted.is-focused)
     -0:34.9.0 emmet:increment-number-by-01 (atom-text-editor.editor.conflicted.is-focused)
  2x -0:34.5.0 emmet:decrement-number-by-01 (atom-text-editor.editor.conflicted.is-focused)
 11x -0:33.8.0 core:page-down (atom-text-editor.editor.conflicted.is-focused)
  4x -0:32.3.0 core:page-up (atom-text-editor.editor.conflicted.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/home/user/projects",
    "disabledPackages": [
      "autosave",
      "language-javascript",
      "typewriter-sounds",
      "language-toml",
      "linter-eslint",
      "linter",
      "atom-beautify",
      "language-clojure",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "language-shellscript",
      "language-property-list"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "merge-conflicts": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-emojis, v2.2.2
autocomplete-modules, v1.3.1
color-picker, v2.0.13
emmet, v2.3.13
file-icons, v1.6.11
highlight-selected, v0.10.1
language-babel, v1.0.0
merge-conflicts, v1.3.7
minimap, v4.16.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
pigments, v0.18.1
project-manager, v2.6.5
pulsing-cursor, v0.3.1
standard-formatter, v1.2.0

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
Nuts. This looks like the same bug as #171; I'll close this in favor of that one to keep discussions centralized.

**Comment by toxickg** [comment]
Sure.

**Comment by abhsri** [comment]
i have same problem how do i solve this

**Comment by prchando** [comment]
Same problem even after restarting the system

**Comment by rkarne** [comment]
same problem even after restarting visual studio
