### ISSUE TITLE
Uncaught Error: Failed to create locked file '.../.git/index.lock...

### ISSUE THREAD

**Issue by averrin** [smashwilson/merge-conflicts#194]
1. Press stage

**Atom Version**: 1.4.0-beta0
**System**: Ubuntu 15.10
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7

### Stack Trace

Uncaught Error: Failed to create locked file '.../.git/index.lock': File exists

```
At /home/user/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189

Error: Failed to create locked file '.../.git/index.lock': File exists
    at Error (native)
    at Function.GitBridge.add (/home/user/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189:15)
    at ResolverView.resolve (/home/user/.atom/packages/merge-conflicts/lib/view/resolver-view.coffee:126:24)
    at HTMLButtonElement.<anonymous> (/usr/share/atom-beta/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom-beta/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/usr/share/atom-beta/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -1:09.7.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.conflicted.is-focused.reversed.normal-mode)
     -1:08.1.0 vim-mode-plus:activate-linewise-visual-mode (atom-text-editor.editor.vim-mode-plus.conflicted.is-focused.reversed.normal-mode)
 22x -1:07.9.0 vim-mode-plus:move-down (atom-text-editor.editor.vim-mode-plus.conflicted.is-focused.visual-mode.linewise)
     -1:05.5.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.conflicted.is-focused.visual-mode.linewise)
     -1:04.8.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.conflicted.is-focused.normal-mode)
  2x -1:04.2.0 vim-mode-plus:delete (atom-text-editor.editor.vim-mode-plus.conflicted.is-focused.normal-mode)
  5x -0:57.3.0 blur (atom-text-editor.editor.vim-mode-plus.conflicted.is-focused.normal-mode)
     -0:52.7.0 command-palette:toggle (atom-text-editor.editor.vim-mode-plus.conflicted.is-focused.normal-mode)
     -0:52.4.0 blur (atom-text-editor.editor.vim-mode-plus.conflicted.is-focused.normal-mode)
  4x -0:44.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 13x -0:42 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:38.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:38.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  7x -0:38.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:26.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-accents-ui)
 13x -0:26.6.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.conflicted)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "web-browser",
      "tool-bar-main",
      "atom-jade",
      "spell-check",
      "seti-icons",
      "atom-color-highlight",
      "local-history",
      "project-view",
      "tool-bar",
      "toolbar-basic",
      "background-tips",
      "image-view",
      "language-csharp",
      "linter-tidy",
      "deprecation-cop",
      "linter-python-pyflakes",
      "opened-files",
      "hyperclick",
      "symbol-gen",
      "symbols-view",
      "symbols-tree-view",
      "run-command",
      "devdocs",
      "neon-selection",
      "vim-mode",
      "ex-mode"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "accents-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.7
accents-ui, v1.1.0
api-docs, v0.0.3
atom-ctags, v4.4.2
atom-jinja2, v0.5.0
auto-reveal-in-sidebar, v0.8.0
autocomplete-paths, v1.0.2
autocomplete-python, v1.2.2
color-picker, v2.0.14
color-picker-service, v0.0.1
color-tabs, v0.1.8
color-tabs-regex, v0.2.3
editorconfig, v1.2.2
emmet, v2.3.17
file-icons, v1.6.13
foldername-tabs, v0.1.5
git-hide, v0.1.2
github-notifications, v0.1.1
javascript-snippets, v1.0.0
language-babel, v2.6.0
language-diff, v0.4.0
language-javascript-better, v1.7.1
language-javascript-jsx, v0.3.7
language-lua, v0.9.4
language-nunjucks, v2.0.0
last-cursor-position, v0.9.0
linter, v1.11.3
linter-eslint, v5.2.6
linter-jscs, v3.2.0
linter-jshint, v1.2.1
linter-pep8, v1.0.1
linter-pylama, v0.2.2
merge-conflicts, v1.3.7
minimap, v4.17.0
minimap-bookmarks, v0.1.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
nerd-treeview, v0.3.1
pigments, v0.19.1
python-iresolve, v0.0.3
python-tools, v0.6.7
quick-highlight, v0.3.9
remember-file-positions, v0.2.0
swackets, v0.9.3
sync-settings, v0.6.0
tidy-tabs, v0.3.0
time-status, v1.1.0
underline-trailing-whitespace, v1.4.0
vim-mode-plus, v0.8.0
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
This looks like it's related to #171 which has been puzzling me for some time.

**Comment by smashwilson** [comment]
Closing as a duplicate; please subscribe on that issue for updates.
