### ISSUE TITLE
Failed to activate merge-conflicts package

### ISSUE THREAD

**Issue by Abhis3798** [smashwilson/merge-conflicts#210]
[Enter steps to reproduce below:]
**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.4
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7

### Stack Trace

Failed to activate the merge-conflicts package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/abhiram/.atom/packages/merge-conflicts/node_modules/space-pen/lib/space-pen.js:9:18)
    at Object.<anonymous> (/home/abhiram/.atom/packages/merge-conflicts/node_modules/space-pen/lib/space-pen.js:634:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
     -0:00.5.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
```

**Comment by smashwilson** [comment]
This looks like a corrupted installation. Try re-installing to see if the dependencies are installed correctly.
