### ISSUE TITLE
Uncaught Error: Cannot find module 'space-pen'

### ISSUE THREAD

**Issue by creekpld** [smashwilson/merge-conflicts#215]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Ubuntu 15.10
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7

### Stack Trace

Uncaught Error: Cannot find module 'space-pen'

```
At module.js:338

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/pld/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:1:13)
    at Object.<anonymous> (/home/pld/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/pld/.atom/packages/merge-conflicts/lib/main.coffee:3:24)
    at Object.<anonymous> (/home/pld/.atom/packages/merge-conflicts/lib/main.coffee:1:1)
    at Module._compile (/opt/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/opt/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateConfig (/opt/atom/resources/app.asar/src/package.js:220:12)
    at PackageManager.<anonymous> (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:55:14)
    at PackageManager.packageHasSettings (/opt/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:658:63)
    at PackageCard.module.exports.PackageCard.hasSettings (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:611:34)
    at PackageCard.module.exports.PackageCard.initialize (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:205:17)
    at PackageCard.View [as constructor] (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new PackageCard (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:22:48)
    at InstallPanel.module.exports.InstallPanel.addPackageViews (/opt/atom/resources/app.asar/node_modules/settings-view/lib/install-panel.js:280:41)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-swift",
      "language-swift",
      "language-swift",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-pigments",
      "minimap"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-atom-api, v0.10.0

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
I notice that merge-conflicts doesn't appear in your "Installed Packages" summary, which strikes me as odd. Was the installation interrupted or corrupted somehow?

Try deleting the `~/.atom/packages/merge-conflicts` directory and re-running `apm install merge-conflicts`.

**Comment by creekpld** [comment]
ok reinstall worked, thx ;)
