### ISSUE TITLE
Uncaught TypeError: Cannot read property 'detect' of undefined

### ISSUE THREAD

**Issue by hybrisCole** [smashwilson/merge-conflicts#216]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7

### Stack Trace

Uncaught TypeError: Cannot read property 'detect' of undefined

```
At /Users/albertocole/.atom/packages/merge-conflicts/lib/main.coffee:27

TypeError: Cannot read property 'detect' of undefined
  at /Users/albertocole/.atom/packages/merge-conflicts/lib/main.coffee:27:27
  at /Users/albertocole/.atom/packages/merge-conflicts/lib/git-bridge.coffee:42:9
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
     -0:46.3.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:32.4.0 command-palette:toggle (atom-pane.pane.active)
     -0:31.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:30 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:30 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:27.7.0 editor:duplicate-lines (atom-pane.pane.active)
     -0:23.5.0 command-palette:toggle (atom-pane.pane.active)
     -0:22.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:21 merge-conflicts:detect (atom-pane.pane.active)
     -0:03.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 merge-conflicts:detect (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "merge-conflicts": {}
}
```

### Installed Packages

```coffee
# User
merge-conflicts, v1.3.7
nuclide, v0.125.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
This looks like a truncated installation to me. Try uninstalling merge-conflicts, restarting Atom competely, then reinstalling.

**Comment by miclaus** [comment]
@smashwilson cannot uninstall (see #241)
