### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by pierreglardon** [smashwilson/merge-conflicts#217]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.5
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:260

Error: spawn ENOTDIR
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at Function.GitBridge.process (/Users/session2/.atom/packages/merge-conflicts/lib/git-bridge.coffee:18:27)
    at Function.GitBridge.withConflicts (/Users/session2/.atom/packages/merge-conflicts/lib/git-bridge.coffee:127:13)
    at Function.MergeState.read (/Users/session2/.atom/packages/merge-conflicts/lib/merge-state.coffee:17:15)
    at Function.MergeConflictsView.detect (/Users/session2/.atom/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:162:16)
    at /Users/session2/.atom/packages/merge-conflicts/lib/main.coffee:27:28
    at Function.GitBridge.locateGitAnd (/Users/session2/.atom/packages/merge-conflicts/lib/git-bridge.coffee:27:7)
    at atom-workspace.<anonymous> (/Users/session2/.atom/packages/merge-conflicts/lib/main.coffee:25:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:00.9.0 merge-conflicts:detect (atom-pane.pane.active)
```

### Config

```json
{
  "core": {},
  "merge-conflicts": {
    "gitPath": "/usr/bin/git/"
  }
}
```

### Installed Packages

```coffee
# User
atom-wordpress, v0.3.0
emmet, v2.4.3
merge-conflicts, v1.3.7
wordpress, v0.2.0
wordpress-api, v1.2.2

# Dev
No dev packages
```

I got this error when I try to use merge-conflicts. I also got this one at the same time : https://github.com/smashwilson/merge-conflicts/issues/161 but I don't find how to fix them :(

**Comment by smashwilson** [comment]
From your configuration, you have `gitPath` set to `/usr/bin/git/` with a trailing slash, so merge-conflicts is interpreting it as a directory instead of a file. Try setting it to `/usr/bin/git` (or unsetting it entirely, that should be on your PATH already).
