### ISSUE TITLE
Uncaught Error: Failed to rename lockfile to '/Users/hernanezequielmartinez/Documents/workspace/l...

### ISSUE THREAD

**Issue by hernanemartinez** [smashwilson/merge-conflicts#218]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.1
**System**: Mac OS X 10.10.5
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.3.7

### Stack Trace

Uncaught Error: Failed to rename lockfile to '/Users/hernanezequielmartinez/Documents/workspace/linkedin-messages/linkeddyn-msgs/.git/objects/32/73856aa90a40c8a6071aa79be49cae3eedc0f0': Permission denied

```
At /Users/hernanezequielmartinez/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189

Error: Failed to rename lockfile to '/Users/hernanezequielmartinez/Documents/workspace/linkedin-messages/linkeddyn-msgs/.git/objects/32/73856aa90a40c8a6071aa79be49cae3eedc0f0': Permission denied
    at Error (native)
    at Function.GitBridge.add (/Users/hernanezequielmartinez/.atom/packages/merge-conflicts/lib/git-bridge.coffee:189:15)
    at ResolverView.resolve (/Users/hernanezequielmartinez/.atom/packages/merge-conflicts/lib/view/resolver-view.coffee:61:15)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:24.3.0 application:add-project-folder (atom-text-editor.editor.is-focused)
     -4:54.3.0 merge-conflicts:detect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  4x -3:30 core:undo (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "merge-conflicts": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
merge-conflicts, v1.3.7

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
:wave: Thanks for taking the time to file an issue here! Unfortunately, this repository is being [deprecated](https://github.com/smashwilson/merge-conflicts/blob/master/docs/announcement.md), so I won't be getting to this one here.

This one should be taken care of by the [new git and GitHub package for Atom](https://github.com/atom/github). If you see something similar, please [file an issue there](https://github.com/atom/github/issues/new) to let us know. Thanks 🙇

**Comment by rezaarifian** [comment]
same me too,, i am using gitkraken on mac os high sierra and get error message.
cannot push every change file.
