### ISSUE TITLE
Failed to load the merge-conflicts package

### ISSUE THREAD

**Issue by MattRiesterer** [smashwilson/merge-conflicts#231]
[Enter steps to reproduce below:]

1. start atom

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.4.2

### Stack Trace

Failed to load the merge-conflicts package

```
At Cannot find module 'property-accessors'

Error: Cannot find module 'property-accessors'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/mriesterer/.atom/packages/merge-conflicts/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/behavior.js:9:23)
    at Object.<anonymous> (/Users/mriesterer/.atom/packages/merge-conflicts/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/behavior.js:120:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/mriesterer/.atom/packages/merge-conflicts/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/helpers.js:5:14)
    at Object.<anonymous> (/Users/mriesterer/.atom/packages/merge-conflicts/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/helpers.js:55:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/mriesterer/.atom/packages/merge-conflicts/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/emissary.js:4:13)
    at Object.<anonymous> (/Users/mriesterer/.atom/packages/merge-conflicts/node_modules/space-pen/node_modules/grim/node_modules/emissary/lib/emissary.js:14:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/mriesterer/.atom/packages/merge-conflicts/node_modules/space-pen/node_modules/grim/lib/grim.js:4:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "language-gfm"
    ],
    "followSymlinks": false,
    "projectHome": "/Users/mriesterer/workspace",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
autocomplete-angular-material, v0.4.0
autocomplete-python, v1.7.2
editorconfig, v1.4.1
hyperclick, vundefined
language-ansible, v0.1.3
language-docker, v1.1.6
language-markdown, v0.12.0
language-puppet, v0.19.1
merge-conflicts, v1.4.2

# Dev
No dev packages
```

**Comment by nelson6e65** [comment]
I'm getting this related issue:

1. Startup Atom.

**Atom Version**: 1.0.11
**System**: Ubuntu 12.04.4
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.4.2


### Stack Trace

Failed to load the merge-conflicts package

```
At /home/jeahm/.atom/packages/merge-conflicts/lib/git/shellout.js:15
    .then((results) => {
                    ^^
Unexpected token =>

/home/jeahm/.atom/packages/merge-conflicts/lib/git/shellout.js:15
    .then((results) => {
                    ^^
SyntaxError: Unexpected token =>
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:435:25)
  at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/jeahm/.atom/packages/merge-conflicts/lib/git/index.js:10:20)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/jeahm/.atom/packages/merge-conflicts/lib/main.coffee:4:12)
  at Object.<anonymous> (/home/jeahm/.atom/packages/merge-conflicts/lib/main.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app.asar/src/package.js:759:34)
  at /opt/atom/resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/opt/atom/resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/opt/atom/resources/app.asar/src/package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (/opt/atom/resources/app.asar/src/atom.js:667:21)
  at Object.<anonymous> (/opt/atom/resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/opt/atom/resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///opt/atom/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///opt/atom/resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "php-getters-setters",
      "line-ending-selector",
      "linter-scss-lint",
      "linter-eslint",
      "php-debug",
      "phpunit",
      "autoclose-html"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```

### Installed Packages

```coffee
# User
atom-text-transformer, v0.7.0
auto-detect-indentation, v1.0.0
auto-indent, v0.5.0
autocomplete-php, v0.3.7
docblockr, v0.7.3
docs-snippets, v0.8.0
exception-reporting, v0.38.1
html-entities, v0.4.0
indentation-indicator, v0.6.0
line-ending-converter, v1.3.2
linter, v1.11.4
linter-bootlint, v1.0.2
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-htmlhint, v1.1.4
linter-pep8, v1.2.1
linter-php, v1.2.0
linter-phpcs, v1.3.2
linter-shellcheck, v1.2.0
linter-xmllint, v1.3.4
merge-conflicts, v1.4.2
metrics, v0.53.1
minimap, v4.23.1
pigments, v0.26.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
@MattRiesterer: That looks like a partial or corrupted install. Try `apm uninstall merge-conflicts && apm install merge-conflicts` at a terminal to reinstall from scratch.

@nelson6e65: That's a different problem: your Atom is too far out of date! The Chromium build with native arrow function support was included a while ago, but more recently than 1.0.11. Try installing the [latest Atom build](https://github.com/atom/atom/releases/tag/v1.7.3).

**Comment by nelson6e65** [comment]
@smashwilson Yes, I know. But I'm using Ubuntu x86, so there is not .deb available in order to update Atom (Or there is it?).

I installed Atom time ago from some kind of PPA repo, but it's outdated (like everything in ~~Ubuntu~~).

I don't like Ubuntu, because all it's a problem to compile everything and I'm not able to build Atom myself in this machine.

There is not a version of this package compatible with this Atom that I could install?

**Comment by smashwilson** [comment]
You could try backporting to v1.3.7 - that was the last release before I started working in natively-supported ES2015. I think that's just:

```bash
apm uninstall merge-conflicts
apm install merge-conflicts@1.3.7
```

**Comment by nelson6e65** [comment]
Thank you! It's working.

This is a nice package! :smile:

**Comment by smashwilson** [comment]
> This is a nice package! :smile: 

Thanks!

> But I'm using Ubuntu x86, so there is not .deb available in order to update Atom (Or there is it?).

Hmm, yeah, I only see an amd64 .deb on [the releases page](https://github.com/atom/atom/releases/tag/v1.7.3). Unfortunately, I suspect that's because Chromium itself dropped 32-bit support a while ago...

**Comment by nelson6e65** [comment]
Neither `.rpm` for Fedora x86. But in my own PC I can build Atom for 32-bit easily in fedora. Actually, I made a [build helper for Fedora](https://github.com/nelson6e65/fedora-atom-builder).

**Comment by MattRiesterer** [comment]
@smashwilson you were right with the corrupted install. After reinstalling everything works fine. This fixes the issue for me.

Thank you

**Comment by smashwilson** [comment]
Fantastic! Glad to hear it. :tada:
