### ISSUE TITLE
merge-conflicts package fails to load on Atom start up

### ISSUE THREAD

**Issue by web-snake** [smashwilson/merge-conflicts#233]
This started happening every time I start Atom. I believe it started happening right after upgrading to the most recent version of merge-conflicts: 1.4.2

Failed to load the merge-conflicts package
/home/dug/.atom/packages/merge-conflicts/lib/git/shellout.js:15
    .then((results) => {
                    ^^
Unexpected token =>
Hide Stack Trace
/home/dug/.atom/packages/merge-conflicts/lib/git/shellout.js:15
    .then((results) => {
                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:435:25)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/home/dug/.atom/packages/merge-conflicts/lib/git/index.js:10:20)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)

**Comment by smashwilson** [comment]
Your version of Atom is out of date! What version do you have?

If you're unable to upgrade to a newer Atom, you can downgrade merge-conflicts to 1.3.7:

```bash
apm uninstall merge-conflicts
apm install merge-conflicts@1.3.7
```

(I should have modified the `engine` field in my package.json when I started using arrow functions, but I didn't. Sorry for the inconvenience!)

**Comment by web-snake** [comment]
Thanks,
it works fine with a more modern Atom install.
