### ISSUE TITLE
Uncaught TypeError: Illegal invocation

### ISSUE THREAD

**Issue by 50Wliu** [smashwilson/merge-conflicts#238]
_From @nobalmohan on May 26, 2016 12:10_

[Enter steps to reproduce below:]

**Atom Version**: 1.7.4
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Illegal invocation

```
At C:\Users\nobal\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:98

TypeError: Illegal invocation
    at Socket.<anonymous> (C:\Users\nobal\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:98:13)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:45.7.0 merge-conflicts:detect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jslint",
      "jshint"
    ]
  },
  "editor": {
    "fontSize": 18,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-beautify, v0.29.7
atom-jshint, v2.0.0
atom-react-native-autocomplete, v0.0.26
atom-react-native-css, v1.1.1
atom-typescript, v8.10.2
autocomplete-plus, v2.31.0
editorconfig, v1.4.1
file-icons, v1.7.12
language-javascript-jsx, v0.3.7
linter, v1.11.4
linter-csslint, v1.3.2
linter-eslint, v7.2.2
linter-jshint, v2.1.0
linter-tidy, v2.1.0
linter-tslint, v0.9.3
merge-conflicts, v1.4.3
nuclide-code-format, v0.0.22
nuclide-flow, v0.0.22
nuclide-installer, v0.0.22
nuclide-type-hint, v0.0.22
php-cs-fixer, v2.5.6
pigments, v0.27.0
react-es6-snippets, v0.3.0
solid-completions, v1.6.3

# Dev
No dev packages
```

_Copied from original issue: atom/atom#11845_

**Comment by 50Wliu** [comment]
Hi @nobalmohan, what were you doing when this happened?

**Comment by 50Wliu** [comment]
_From @nobalmohan on May 26, 2016 18:2_

@50Wliu  I am using this plugin https://atom.io/packages/merge-conflicts, it happened after I resolved my merge conflict and saved the changes ( click of Stage button ).

**Comment by nelson6e65** [comment]
I'm running into the same issue:

1. Edit file with conflicts
2. Click Stage button 

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Illegal invocation

```
At C:\Users\nmartell\AppData\Local\atom\app-1.7.3\resources\app.asar\src\buffered-process.js:87

TypeError: Illegal invocation
    at Socket.<anonymous> (C:\Users\nmartell\AppData\Local\atom\app-1.7.3\resources\app.asar\src\buffered-process.js:87:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
     -8:49 tree-view:show-in-file-manager (span.name.icon.icon-file-directory)
     -7:49.8.0 merge-conflicts:detect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:59.3.0 core:paste (atom-text-editor#merge-conflicts.gitPath.editor.mini.is-focused)
     -1:39.4.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
  2x -1:14.8.0 core:undo (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  6x -1:02.3.0 core:backspace (atom-text-editor.editor.conflicted.is-focused)
     -0:43.5.0 core:save (atom-text-editor.editor.conflicted.is-focused)
     -0:36.3.0 merge-conflicts:detect (atom-text-editor.editor.conflicted.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "php-debug"
    ]
  },
  "editor": {
    "invisibles": {},
    "preferredLineLength": 100,
    "showIndentGuide": true,
    "softWrap": true,
    "tabLength": 24
  }
}
```

### Installed Packages

```coffee
# User
atom-text-transformer, v0.7.0
auto-detect-indentation, v1.0.0
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-php, v0.3.7
docblockr, v0.7.3
docs-snippets, v0.8.0
html-entities, v0.4.0
indentation-indicator, v0.6.0
language-blade, v0.25.2
language-latte, v0.3.1
line-ending-converter, v1.3.2
linter, v1.11.4
linter-bootlint, v1.0.2
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-eslint, v7.2.2
linter-pep8, v1.3.0
linter-php, v1.2.0
linter-phpcs, v1.4.0
linter-xmllint, v1.3.4
merge-conflicts, v1.4.3
minimap, v4.23.5
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by ftaurino** [comment]
same here, on linux, almost same packages list.

**Comment by vischlatter** [comment]
Same here, running on Windows 10.
