### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by PierreGUI** [smashwilson/merge-conflicts#242]
Steps to reproduce below:
1. Merge branch into another (with some conflicts)
2. Fix conflicts, save file
3. Press "Stage" button from popup "We're done here" (doesn't work here)
4..n: press again until error occurs (I also closed the tab/file at some point)

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.4.4
### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056

Error: Cannot decorate a destroyed marker
    at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1056:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1400:33)
    at SideView.decorate (/Users/pierre/.atom/packages/merge-conflicts/lib/view/side-view.coffee:49:27)
    at SideView.detectDirty (/Users/pierre/.atom/packages/merge-conflicts/lib/view/side-view.coffee:74:6)
    at ConflictedEditor.detectDirty (/Users/pierre/.atom/packages/merge-conflicts/lib/conflicted-editor.coffee:115:7)
    at /Users/pierre/.atom/packages/merge-conflicts/lib/conflicted-editor.coffee:71:45
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1378:25
```
### Commands

```
 23x -5:01.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:59.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:58.4.0 project-find:show (atom-text-editor.editor.is-focused)
     -4:58.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:57.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:15.5.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -4:15.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -4:14.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:14.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:59 core:close (atom-text-editor.editor.is-focused)
     -1:42.5.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:40.7.0 merge-conflicts:detect (atom-text-editor.editor.is-focused)
  2x -1:06.0 core:save (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:15.7.0 core:close (atom-text-editor.editor.conflicted.is-focused)
     -0:10.1.0 core:save (atom-text-editor.editor.conflicted.is-focused)
     -0:02.5.0 core:close (atom-text-editor.editor.conflicted.is-focused)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "keybinding-resolver",
      "language-csharp",
      "language-go",
      "language-make",
      "language-mustache",
      "language-perl",
      "metrics",
      "spell-check",
      "welcome",
      "highlight-selected",
      "link",
      "language-toml",
      "language-less",
      "git-diff",
      "release-notes",
      "titanium-alloy"
    ],
    "ignoredNames": [
      "build/",
      "build",
      "Resources/",
      "Resources",
      ".project",
      "*.pyc"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
coffee-compile, v0.21.1
docblockr, v0.7.3
hyperclick, v0.0.36
language-haml, v0.24.0
language-javascript-jsx, v0.3.7
language-tss, v0.4.0
linter, v1.11.4
linter-eslint, v7.2.2
linter-golinter, v1.2.0
merge-conflicts, v1.4.4
pigments, v0.29.1
pretty-json, v1.4.1
tabs-to-spaces, v1.0.2
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by smashwilson** [comment]
:wave: Thanks for taking the time to file an issue here! Unfortunately, this repository is being [deprecated](https://github.com/smashwilson/merge-conflicts/blob/master/docs/announcement.md), so I won't be getting to this one here.

This one should be taken care of by the [new git and GitHub package for Atom](https://github.com/atom/github) because there's no stage button. If you see something similar, please [file an issue there](https://github.com/atom/github/issues/new) to let us know. Thanks 🙇

**Comment by PierreGUI** [comment]
Cool!
Merge-conflit was a must have, switching to github-atom today ;)
Cheers
