### ISSUE TITLE
Cannot read property 'registerContextApi' of undefined

### ISSUE THREAD

**Issue by iki** [smashwilson/merge-conflicts#259]
Atom: 1.13.1 ia32
Package: merge-conflicts 1.4.4

Failed to activate the merge-conflicts package
```
TypeError: Cannot read property 'registerContextApi' of undefined
    at Object.activate (file:///C:/Users/iki/.atom/packages/merge-conflicts/lib/main.coffee:15:23)
    at Package.module.exports.Package.activateNow (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:191:19)
    at C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:164:32
    at Package.module.exports.Package.measure (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:94:15)
    at C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:157:26
    at Package.module.exports.Package.activate (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package.js:154:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\iki\AppData\Local\atom\app-1.13.1\resources\app.asar\src\atom-environment.js:831:28
```

**Comment by smashwilson** [comment]
:wave: Thanks for taking the time to file an issue here! Unfortunately, this repository is being [deprecated](https://github.com/smashwilson/merge-conflicts/blob/master/docs/announcement.md), so I won't be getting to this one here.

This one should be taken care of by the [new git and GitHub package for Atom](https://github.com/atom/github). If you see something similar, please [file an issue there](https://github.com/atom/github/issues/new) to let us know. Thanks 🙇
