### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

### ISSUE THREAD

**Issue by csjones** [smashwilson/merge-conflicts#97]
Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package, v1.2.8

### Steps To Reproduce

1. CMD + Shift + P, Enter
2. Clicked On "Use Me ^2" with no changes to file
3. Clicked Stage File

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration.js:44

TypeError: Cannot read property 'onDidDestroy' of undefined
  at new Decoration (/Applications/Atom.app/Contents/Resources/app/src/decoration.js:44:49)
  at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1174:20)
  at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1212:33)
  at SideView.module.exports.SideView.decorate (/Users/csjones/.atom/packages/merge-conflicts/lib/side-view.coffee:36:29)
  at SideView.module.exports.SideView.detectDirty (/Users/csjones/.atom/packages/merge-conflicts/lib/side-view.coffee:61:6)
  at ConflictMarker.module.exports.ConflictMarker.detectDirty (/Users/csjones/.atom/packages/merge-conflicts/lib/conflict-marker.coffee:81:7)
  at /Users/csjones/.atom/packages/merge-conflicts/lib/conflict-marker.coffee:49:37
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:25

```

/cc @atom/core

**Comment by smashwilson** [comment]
There's more discussion on #98, so I'll mark this one as the dup, even though you were first. :bow: :point_right:
