### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

### ISSUE THREAD

**Issue by benogle** [smashwilson/merge-conflicts#98]
_From @tkdan235 on December 12, 2014 18:50_

Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

**Atom Version**: 0.154.0
**System**: Mac OS X 10.10.1
**Thrown From**: [merge-conflicts](https://github.com/smashwilson/merge-conflicts) package

### Steps To Reproduce

1. Using merge conflict package, I select "theirs" when dealing with a conflict and got this error.

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/src/decoration.js:44

TypeError: Cannot read property 'onDidDestroy' of undefined
  at new Decoration (/Applications/Atom.app/Contents/Resources/app/src/decoration.js:44:49)
  at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:1174:20)
  at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1212:33)
  at SideView.module.exports.SideView.decorate (/Users/daniel/.atom/packages/merge-conflicts/lib/side-view.coffee:36:29)
  at SideView.module.exports.SideView.detectDirty (/Users/daniel/.atom/packages/merge-conflicts/lib/side-view.coffee:61:6)
  at ConflictMarker.module.exports.ConflictMarker.detectDirty (/Users/daniel/.atom/packages/merge-conflicts/lib/conflict-marker.coffee:81:7)
  at /Users/daniel/.atom/packages/merge-conflicts/lib/conflict-marker.coffee:49:37
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:25

```

_Copied from original issue: atom/atom#4580_

**Comment by michaeljcalkins** [comment]
Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined
c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\decoration.js:44
Hide Stack Trace
TypeError: Cannot read property 'onDidDestroy' of undefined
  at new Decoration (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\decoration.js:44:49)
  at DisplayBuffer.module.exports.DisplayBuffer.decorateMarker (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\display-buffer.js:1204:20)
  at TextEditor.module.exports.TextEditor.decorateMarker (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:1216:33)
  at SideView.module.exports.SideView.decorate (c:\Users\Michael J. Calkins\.atom\packages\merge-conflicts\lib\side-view.coffee:36:29)
  at SideView.module.exports.SideView.detectDirty (c:\Users\Michael J. Calkins\.atom\packages\merge-conflicts\lib\side-view.coffee:61:6)
  at ConflictMarker.module.exports.ConflictMarker.detectDirty (c:\Users\Michael J. Calkins\.atom\packages\merge-conflicts\lib\conflict-marker.coffee:81:7)
  at c:\Users\Michael J. Calkins\.atom\packages\merge-conflicts\lib\conflict-marker.coffee:49:37
  at Emitter.module.exports.Emitter.emit (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:82:11)
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:1142:25

**Comment by smashwilson** [comment]
Strange, I can't replicate this one, now. I'd definitely seen it myself a few times, too.

My suspicion is that [DisplayBuffer.getMarker()](https://github.com/atom/atom/blob/60970d6cec5388d777eef060892f0f919ee805e4/src/display-buffer.coffee#L944) is returning a null marker, which must mean that there's some way that `Side.marker` is being populated incorrectly - with a marker that doesn't correspond to the right `DisplayBuffer`. I'm not seeing how that could happen, though. Those markers are created by `Conflict.all`, which uses the same TextEditor instance throughout.

I'll keep an eye out for this, because if I can replicate it reliably then I can dump what markers are being used where and figure out what's going wrong. For now, though, I don't want to hold up the Shadow-DOM release with this, because it's pretty broken and I want to push a functional release out soon-ish.

**Comment by smashwilson** [comment]
Actually, I have a hunch: I suspect that the `detectDirty` handler is being invoked for a `Side` that has already deleted its marker. I should `null` it out when it's destroyed and test for that in `detectDirty`.

**Comment by smashwilson** [comment]
I haven't seen this for a while, now - that might have done it. I'll close this for now.
